spring:
  datasource:
    password: cnc_news_201712!
    username: root
    url: jdbc:mysql://101.200.137.178:3306/ftkms_spareparts?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
